
server:
  port: 44391
  servlet:
    context-path: /oven-temperature-store
  forward-headers-strategy: framework

spring:
  application:
    name: oven-temperature-store
  profiles:
    active: DEV

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 600000 # 10 minutes

# Application properties
app:
  polling-result-file-path: ovens_temperatures.json
  polling-frequency: 120000 # 2 minutes